(package "atl-markup" "0.1.5" "Automatically truncate lines for markup languages")

(website-url "https://github.com/jcs-elpa/atl-markup")
(keywords "convenience" "automatic" "truncate" "visual" "lines")

(package-file "atl-markup.el")

(source "melpa")

(depends-on "emacs" "24.3")

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
